name: Release snapshot

on:
  push:
    branches: [ master ]

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Restore build cache
        run: echo dummy step for now
      - name: Publish generator snapshot
        run: G_VERSION="dev-$(git rev-parse HEAD)-gen" make publish-generator;
      - name: Publish generated snapshot
        run: VERSION="dev-$(git rev-parse HEAD)" make publish;